SuperSeller.Web/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SuperSeller.Common.Admin.BindingModels;
using SuperSeller.Models;
using SuperSeller.Services.Admin.Interfaces;

namespace SuperSeller.Web.Areas.Admin.Controllers
{
    public class UsersController : AdminController
    {
        private readonly IUsersService usersService;

        public UsersController(IUsersService usersService)
        {
            this.usersService = usersService;
        }


        public IActionResult Index()
        {
            var model = usersService.GetAllUsers().Result;

            return View(model);
        }

        public IActionResult Details(string id)
        {
            var model = usersService.GetUser(id).Result;

            return View(model);
        }

        [HttpGet]
        public IActionResult ChangeUserPassword(string id)
        {
            var user = usersService.GetUser(id);
            var model = new ChangePasswordBindingModel()
            {
                Id = id,
                Username = user.Result.UserName
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult ChangeUserPassword(ChangePasswordBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["errorMessage"] = "Invalid input!";
                return View();
            }

            var isChange = usersService.ChangeUserPassword(model.Id, model.Password);

            if (!isChange.Result)
            {
                TempData["errorMessage"] = "Something goes wrong.";
            }

            TempData["successMessage"] = $"{model.Username}'s password has been changed successfully!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Ban(string id)
        {
            var user = usersService.GetUser(id);
            TempData["Username"] = user.Result.UserName;
            return View();
        }

        [HttpPost]
        public IActionResult Ban(BanUserBindingModel model, string id)
        {
            var user = usersService.GetUser(id);
            var isLock = usersService.BanUser(id, model.EndDate);

            if (!isLock.Result)
            {
                this.TempData["errorMessage"] = $"{user.Result.UserName}'s account wasn't banned!";
            }
            this.TempData["successMessage"] = $"{user.Result.UserName}'s account was banned to {model.EndDate}";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Unban(string id)
        {
            var user = usersService.GetUser(id).Result;
            var isUnLock = usersService.UnbanUser(id);
            if (!isUnLock)
            {
                this.TempData["errorMessage"] = $"{user.UserName}'s account wasn't unlock!";
            }
            this.TempData["successMessage"] = $"{user.UserName}'s account was unlocked.";
            return RedirectToAction("Index");
        }
    }
}

SuperSeller.Web/Areas/Admin/Pages/Category/All.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SuperSeller.Common.Admin.ViewModels;
using SuperSeller.Services.Admin.Interfaces;

namespace SuperSeller.Web.Areas.Admin.Pages.Category
{
    public class AllModel : PageModel
    {
        private readonly ICategoryService categoryService;

        public ICollection<CategoryConciseViewModel> Categories { get; set; }

        public AllModel(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }

        public void OnGet()
        {
            Categories = categoryService.GetAllCategories().Result;
        }

        public IActionResult OnGetDelete(int id)
        {
            categoryService.Delete(id);

            return RedirectToPage("All");
        }
    }
}

SuperSeller.Web/Areas/Identity/Controllers/AdsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SuperSeller.Models;
using SuperSeller.Services.Users.Interfaces;

namespace SuperSeller.Web.Areas.Identity.Controllers
{
    [Area("Identity")]
    public class AdsController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly IAdService adService;

        public AdsController(UserManager<User> userManager, IAdService adService)
        {
            this.userManager = userManager;
            this.adService = adService;
        }

        public IActionResult Delete(int id)
        {

            var user = userManager.GetUserAsync(this.User).Result;
            if (user == null)
            {
                this.ViewData["errorMessage"] = "You do not have permision to this ad!";
                return Redirect("/");
            }
            var isAdmin = userManager.IsInRoleAsync(user, "Administrator").Result;
            var isDelete = adService.DeleteAd(id, user, isAdmin);
            if (isDelete)
            {
                this.ViewData["successMessage"] = "Ad is successfully removed";
                return Redirect("/");
            }

            this.ViewData["errorMessage"] = "You do not have permision to this ad!";
            return Redirect("/");
        }
    }
}

SuperSeller.Web/Areas/Admin/Views/Shared/DisplayTemplates/AdsConciseViewModel.cshtml
@model AdsConciseViewModel

<tr>
    <td>@Model.Title</td>
    <td>@Model.Price</td>
    <td>@Model.Condition</td>
    <td>@Model.Viewing</td>
    <td>@Html.DisplayFor(model => model.PromoEnable)</td>
    <td>
        <a asp-area="" asp-page="/Ad/Details" asp-route-id="@Model.Id"
           class="btn btn-default">
            Details
        </a>
        <a asp-area="Identity" asp-controller="Ads" asp-action="Delete" asp-route-id="@Model.Id"
           class="btn btn-warning">
            Delete
        </a>
    </td>
</tr>

SuperSeller.Web/Areas/Admin/Views/Shared/DisplayTemplates/CategoryConciseViewModel.cshtml
@model CategoryConciseViewModel

<tr>
    <td>@Model.Name</td>
    <td>@Model.SubCotegoriesCount</td>
    <td>
        <a asp-area="Admin" asp-page="/Category/Details" asp-route-id="@Model.Id"
           class="btn btn-default">
            Details
        </a>
        <a asp-area="Admin" asp-page="/SubCategory/Create" asp-route-id="@Model.Id"
           class="btn btn-primary">
            Create SubCategory
        </a>
        <a asp-area="Admin" asp-page-handler="Delete" asp-route-id="@Model.Id"
           class="btn btn-danger">
            Delete
        </a>
    </td>
</tr>

SuperSeller.Web/Areas/Admin/Views/Shared/DisplayTemplates/SubCategoryConciseViewModel.cshtml
@model SubCategoryConciseViewModel

<tr>
    <td>@Model.Name</td>
    <td>@Model.AdsCount</td>
    <td>
        <a asp-controller="SubCategory" asp-action="Details" asp-route-id="@Model.Id"
           class="btn btn-default">
            Details
        </a>
        <a asp-area="Identity" asp-controller="Ad" asp-action="Create" asp-route-id="@Model.Id"
           class="btn btn-primary">
            Create Ad
        </a>
        <a asp-area="Admin" asp-page="/SubCategory/Delete" asp-route-id="@Model.Id"
           class="btn btn-danger">
            Delete
        </a>
    </td>
</tr>

SuperSeller.Web/Areas/Admin/Views/Shared/DisplayTemplates/UsersConciseViewModel.cshtml
@model UsersConciseViewModel

<tr>
    <td>@Model.UserName</td>
    <td>@Model.Email</td>
    <td>@Model.City</td>
    <td>@Model.RegisteredDate</td>
    <td>@Model.Ads</td>
    <td>@Html.DisplayFor(model => model.IsAdmin)</td>
    <td>
        <a asp-area="Admin" asp-controller="Users" asp-action="Details" asp-route-id="@Model.Id"
           class="btn btn-default">
            Details
        </a>
        <a asp-area="Admin" asp-controller="Users" asp-action="ChangeUserPassword" asp-route-id="@Model.Id"
           class="btn btn-warning">
            Change password
        </a>
        @if (@Model.isLock)
        {
            <a asp-area="Admin" asp-controller="Users" asp-action="Unban" asp-route-id="@Model.Id"
               class="btn btn-primary">
                Unban
            </a>
        }
        else
        {
            <a asp-area="Admin" asp-controller="Users" asp-action="Ban" asp-route-id="@Model.Id"
               class="btn btn-danger">
                Ban
            </a>
        }
    </td>
</tr>